#!/usr/bin/env bash
##################################
# **** DO NOT EDIT THIS FILE ****
# This file is managed by Salt
# Any changes will be overwritten
##################################

alias sys='sudo systemctl'
alias fw='sudo firewall-cmd'
