#!/usr/bin/env bash
##################################
# **** DO NOT EDIT THIS FILE ****
# This file is managed by Salt
# Any changes will be overwritten
##################################

source /opt/dotfiles/complete-hosts.sh
source /opt/dotfiles/git-completion.sh
