##################################
# **** DO NOT EDIT THIS FILE ****
# This file is managed by Salt
# Any changes will be overwritten
##################################
vcl 4.0;
backend default {
    .host = "{{ settings['backend_address'] }}";
    .port = "{{ settings['backend_port'] }}";
}
