include:
  - salt.minion
  - php
  - nginx
  - redis
  - mysql.mycnf
  - mysql.client
  - applications.wordpress
  - applications.wordpress.directories
  - applications.wordpress.config
  - nfs.client
